# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigen_compute_single_entry_of_diagonal_matrix_cpp <- function(M, j) {
    .Call(`_SeqExpMatch_eigen_compute_single_entry_of_diagonal_matrix_cpp`, M, j)
}

eigen_Xt_times_diag_w_times_X_cpp <- function(X, w) {
    .Call(`_SeqExpMatch_eigen_Xt_times_diag_w_times_X_cpp`, X, w)
}

compute_weighted_sqd_distances_cpp <- function(x_new, X_all_scaled_col_subset, reservoir_indices, covariate_weights) {
    .Call(`_SeqExpMatch_compute_weighted_sqd_distances_cpp`, x_new, X_all_scaled_col_subset, reservoir_indices, covariate_weights)
}

fast_logistic_regression_cpp <- function(X, y, start, eps_f = 1e-8, eps_g = 1e-5, maxit = 300L) {
    .Call(`_SeqExpMatch_fast_logistic_regression_cpp`, X, y, start, eps_f, eps_g, maxit)
}

matrix_rank_cpp <- function(A, tol = 1e-12) {
    .Call(`_SeqExpMatch_matrix_rank_cpp`, A, tol)
}

fast_ols_cpp <- function(X, y) {
    .Call(`_SeqExpMatch_fast_ols_cpp`, X, y)
}

fast_ols_with_var_cpp <- function(X, y, j = 2L) {
    .Call(`_SeqExpMatch_fast_ols_with_var_cpp`, X, y, j)
}

sample_int_replace_cpp <- function(n, size) {
    .Call(`_SeqExpMatch_sample_int_replace_cpp`, n, size)
}

scale_columns_cpp <- function(X) {
    .Call(`_SeqExpMatch_scale_columns_cpp`, X)
}

shuffle_cpp <- function(w) {
    .Call(`_SeqExpMatch_shuffle_cpp`, w)
}

compute_bootstrapped_weighted_sqd_distances_cpp <- function(X_all_scaled_col_subset, covariate_weights, t, B) {
    .Call(`_SeqExpMatch_compute_bootstrapped_weighted_sqd_distances_cpp`, X_all_scaled_col_subset, covariate_weights, t, B)
}

which_cols_vary_cpp <- function(X) {
    .Call(`_SeqExpMatch_which_cols_vary_cpp`, X)
}

