# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fill_i_b_with_matches_loop_cpp <- function(i_b, match_indic, ms_b, i_b_idx) {
    invisible(.Call(`_SeqExpMatch_fill_i_b_with_matches_loop_cpp`, i_b, match_indic, ms_b, i_b_idx))
}

eigen_compute_single_entry_on_diagonal_of_inverse_matrix_cpp <- function(M, j) {
    .Call(`_SeqExpMatch_eigen_compute_single_entry_on_diagonal_of_inverse_matrix_cpp`, M, j)
}

eigen_Xt_times_diag_w_times_X_cpp <- function(X, w) {
    .Call(`_SeqExpMatch_eigen_Xt_times_diag_w_times_X_cpp`, X, w)
}

fast_ols_cpp <- function(X, y) {
    .Call(`_SeqExpMatch_fast_ols_cpp`, X, y)
}

mean_cpp <- function(x) {
    .Call(`_SeqExpMatch_mean_cpp`, x)
}

var_cpp <- function(x) {
    .Call(`_SeqExpMatch_var_cpp`, x)
}

beta_loglik_cpp <- function(y, mu, phi, wt) {
    .Call(`_SeqExpMatch_beta_loglik_cpp`, y, mu, phi, wt)
}

beta_dev_resids_cpp <- function(y, mu, phi, wt) {
    .Call(`_SeqExpMatch_beta_dev_resids_cpp`, y, mu, phi, wt)
}

beta_aic_cpp <- function(y, mu, phi, wt) {
    .Call(`_SeqExpMatch_beta_aic_cpp`, y, mu, phi, wt)
}

compute_proportional_mahal_distances_cpp <- function(xt_prev, X_prev, reservoir_indices, S_xs_inv) {
    .Call(`_SeqExpMatch_compute_proportional_mahal_distances_cpp`, xt_prev, X_prev, reservoir_indices, S_xs_inv)
}

compute_weighted_sqd_distances_cpp <- function(x_new, X_all_scaled_col_subset, reservoir_indices, covariate_weights) {
    .Call(`_SeqExpMatch_compute_weighted_sqd_distances_cpp`, x_new, X_all_scaled_col_subset, reservoir_indices, covariate_weights)
}

matrix_rank_cpp <- function(A, tol = 1e-12) {
    .Call(`_SeqExpMatch_matrix_rank_cpp`, A, tol)
}

fast_ols_with_var_cpp <- function(X, y, j = 2L) {
    .Call(`_SeqExpMatch_fast_ols_with_var_cpp`, X, y, j)
}

sample_int_replace_cpp <- function(n, size) {
    .Call(`_SeqExpMatch_sample_int_replace_cpp`, n, size)
}

scale_columns_cpp <- function(X) {
    .Call(`_SeqExpMatch_scale_columns_cpp`, X)
}

shuffle_cpp <- function(w) {
    .Call(`_SeqExpMatch_shuffle_cpp`, w)
}

neg_loglik_nb_cpp <- function(theta, beta, X, y) {
    .Call(`_SeqExpMatch_neg_loglik_nb_cpp`, theta, beta, X, y)
}

match_diffs_cpp <- function(w, match_indic, y, X, m) {
    .Call(`_SeqExpMatch_match_diffs_cpp`, w, match_indic, y, X, m)
}

compute_bootstrapped_weighted_sqd_distances_cpp <- function(X_all_scaled_col_subset, covariate_weights, t, B) {
    .Call(`_SeqExpMatch_compute_bootstrapped_weighted_sqd_distances_cpp`, X_all_scaled_col_subset, covariate_weights, t, B)
}

which_cols_vary_cpp <- function(X) {
    .Call(`_SeqExpMatch_which_cols_vary_cpp`, X)
}

