# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

which_cols_vary_cpp <- function(X) {
    .Call('_SeqExpMatch_which_cols_vary_cpp', PACKAGE = 'SeqExpMatch', X)
}

