// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_weighted_sqd_distances_cpp
NumericVector compute_weighted_sqd_distances_cpp(NumericVector x_new, NumericMatrix X_all_scaled_col_subset, IntegerVector reservoir_indices, NumericVector covariate_weights);
RcppExport SEXP _SeqExpMatch_compute_weighted_sqd_distances_cpp(SEXP x_newSEXP, SEXP X_all_scaled_col_subsetSEXP, SEXP reservoir_indicesSEXP, SEXP covariate_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_new(x_newSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_all_scaled_col_subset(X_all_scaled_col_subsetSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type reservoir_indices(reservoir_indicesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type covariate_weights(covariate_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_weighted_sqd_distances_cpp(x_new, X_all_scaled_col_subset, reservoir_indices, covariate_weights));
    return rcpp_result_gen;
END_RCPP
}
// fast_logistic_regression_cpp
List fast_logistic_regression_cpp(const arma::mat& X, const arma::vec& y, int max_iter, double tol);
RcppExport SEXP _SeqExpMatch_fast_logistic_regression_cpp(SEXP XSEXP, SEXP ySEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_logistic_regression_cpp(X, y, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// fast_logistic_regression_with_sd_cpp
List fast_logistic_regression_with_sd_cpp(const arma::mat& X, const arma::vec& y, int max_iter, double tol);
RcppExport SEXP _SeqExpMatch_fast_logistic_regression_with_sd_cpp(SEXP XSEXP, SEXP ySEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_logistic_regression_with_sd_cpp(X, y, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// matrix_rank_cpp
int matrix_rank_cpp(const Eigen::MatrixXd& A, double tol);
RcppExport SEXP _SeqExpMatch_matrix_rank_cpp(SEXP ASEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_rank_cpp(A, tol));
    return rcpp_result_gen;
END_RCPP
}
// fast_ols_cpp
List fast_ols_cpp(const arma::mat& X, const arma::vec& y);
RcppExport SEXP _SeqExpMatch_fast_ols_cpp(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(fast_ols_cpp(X, y));
    return rcpp_result_gen;
END_RCPP
}
// fast_ols_with_sd_cpp
List fast_ols_with_sd_cpp(const arma::mat& X, const arma::vec& y);
RcppExport SEXP _SeqExpMatch_fast_ols_with_sd_cpp(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(fast_ols_with_sd_cpp(X, y));
    return rcpp_result_gen;
END_RCPP
}
// sample_int_replace_cpp
IntegerVector sample_int_replace_cpp(int n, int size);
RcppExport SEXP _SeqExpMatch_sample_int_replace_cpp(SEXP nSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_int_replace_cpp(n, size));
    return rcpp_result_gen;
END_RCPP
}
// scale_columns_cpp
arma::mat scale_columns_cpp(const arma::mat& X);
RcppExport SEXP _SeqExpMatch_scale_columns_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(scale_columns_cpp(X));
    return rcpp_result_gen;
END_RCPP
}
// shuffle_cpp
NumericVector shuffle_cpp(NumericVector w);
RcppExport SEXP _SeqExpMatch_shuffle_cpp(SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(shuffle_cpp(w));
    return rcpp_result_gen;
END_RCPP
}
// compute_bootstrapped_weighted_sqd_distances_cpp
NumericVector compute_bootstrapped_weighted_sqd_distances_cpp(NumericMatrix X_all_scaled_col_subset, NumericVector covariate_weights, int t, int B);
RcppExport SEXP _SeqExpMatch_compute_bootstrapped_weighted_sqd_distances_cpp(SEXP X_all_scaled_col_subsetSEXP, SEXP covariate_weightsSEXP, SEXP tSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X_all_scaled_col_subset(X_all_scaled_col_subsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type covariate_weights(covariate_weightsSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_bootstrapped_weighted_sqd_distances_cpp(X_all_scaled_col_subset, covariate_weights, t, B));
    return rcpp_result_gen;
END_RCPP
}
// which_cols_vary_cpp
LogicalVector which_cols_vary_cpp(NumericMatrix X);
RcppExport SEXP _SeqExpMatch_which_cols_vary_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(which_cols_vary_cpp(X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SeqExpMatch_compute_weighted_sqd_distances_cpp", (DL_FUNC) &_SeqExpMatch_compute_weighted_sqd_distances_cpp, 4},
    {"_SeqExpMatch_fast_logistic_regression_cpp", (DL_FUNC) &_SeqExpMatch_fast_logistic_regression_cpp, 4},
    {"_SeqExpMatch_fast_logistic_regression_with_sd_cpp", (DL_FUNC) &_SeqExpMatch_fast_logistic_regression_with_sd_cpp, 4},
    {"_SeqExpMatch_matrix_rank_cpp", (DL_FUNC) &_SeqExpMatch_matrix_rank_cpp, 2},
    {"_SeqExpMatch_fast_ols_cpp", (DL_FUNC) &_SeqExpMatch_fast_ols_cpp, 2},
    {"_SeqExpMatch_fast_ols_with_sd_cpp", (DL_FUNC) &_SeqExpMatch_fast_ols_with_sd_cpp, 2},
    {"_SeqExpMatch_sample_int_replace_cpp", (DL_FUNC) &_SeqExpMatch_sample_int_replace_cpp, 2},
    {"_SeqExpMatch_scale_columns_cpp", (DL_FUNC) &_SeqExpMatch_scale_columns_cpp, 1},
    {"_SeqExpMatch_shuffle_cpp", (DL_FUNC) &_SeqExpMatch_shuffle_cpp, 1},
    {"_SeqExpMatch_compute_bootstrapped_weighted_sqd_distances_cpp", (DL_FUNC) &_SeqExpMatch_compute_bootstrapped_weighted_sqd_distances_cpp, 4},
    {"_SeqExpMatch_which_cols_vary_cpp", (DL_FUNC) &_SeqExpMatch_which_cols_vary_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_SeqExpMatch(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
